### ISSUE TITLE
tcp/ip三次握手,四次挥手,为什么挥手多一次,最后一次挥手的作用是什么?

### ISSUE THREAD

**Issue by phpforlan** [phpforlan/ArtisanPHP#20]
tcp/ip三次握手,四次挥手,为什么挥手多一次,最后一次挥手的作用是什么?

**Comment by zhangciba** [comment]
首先，我想针对问题说一下，这个问题的提问方式不对，首先，三次握手是对TCP连接建立过程的一个形象的描述，实际上，官方并没有这种称呼，这是大家为了方便理解才这么称呼的。所以提问应该这么问，“TCP连接建立过程是三次握手，连接释放过程总共有四次操作，两者的过程是怎样的，为何连接释放过程多了一次确认。”。

另外，并没有四次挥手这个说法，无论是教材还是网络上，四次挥手这个说法非常不规范。

那么现在来回答为何连接建立是三次，而释放是四次呢。TCP连接其实是一个双向的连接，例如说，A与B两台电脑建立TCP连接时，实际A到B和B到A时看做两条通道的。在TCP连接建立的过程中，A向B发送连接请求，B需要发挥连接确认之后，这个时候其实连接已经建立了，但是为何还有A需要再次向B发送一个确认报文呢，因为网络不稳定，之前可能网络中会有很多失效的连接请求报文，如果没有确A再次确认的过程，那么如果有些失效报文又被重新受到，那么会影响当前的连接，因此是三次。这个时候，连接建立了，A与B可以相互通信。

连接释放的时候，实际上是其中一方，如A提出了释放请求，B收到后进行了报文确认，那么A到B的连接就释放了，这个时候，B还是可以向A发送数据，而且A会直接接收，到了B数据发送完了，B再向A发送请求释放的请求，B进入超时等待阶段，如果A及时发送连接中断确认，那么B就释放了B到A的连接，如果没有收到，超过一段时间，自动释放。

因此导致这个的主要原因是建立连接和释放连接的过程不一样，3和4没有具体的联系。

再说说这个出题人的思维，他想考察的就是你对TCP连接建立和释放的原理的理解，而不是3和4的区别。
（ps:这是计算机网络里面很基础的知识，虽然我不一定回答对了，但是我大部分都记得，所以，基础知识，能够一次学习好，就不要学很多次）

**Comment by jessejyang** [comment]
> 这个时候，B还是可以向A发送数据，而且A会直接接收，到了B数据发送完了，B再向A发送请求释放的请求

@zhangciba 抱歉，这么久，冒昧的提出自己的疑问，关于引用部分，如果 B 为发送端，A 作为接收端，为了保证可靠性，A 是否需要回复 ACK？如果 B 为接收端（只发送 ACK），A 作为发送端（此时不会发送数据），此时是否代表了发送已经完成（即发送端收到了所有 ACK），那么第二次，第三次挥手是不是可以合并？

谢谢您的回复。

**Comment by catcatching** [comment]
看了楼上的回答，总结来说，断开连接需要多一次操作主要是因为断开连接前可能还有部分数据并未发送完，所以确认断开对方的连接和发送断开自己连接的请求两次操作中间存在一定时间导致不能像建立连接时确认建立和请求建立两个操作同时进行

**Comment by Ryanyanglibin** [comment]
对的




| |
Ryan
|
|
邮箱：yangdabin@163.com
|

Signature is customized by Netease Mail Master

在2019年12月18日 11:17，catcatching 写道：

看了楼上的回答，总结来说，断开连接需要多一次操作主要是因为断开连接前可能还有部分数据并未发送完，所以确认断开对方的连接和发送断开自己连接的请求两次操作中间存在一定时间导致不能像建立连接时确认建立和请求建立两个操作同时进行
