### ISSUE TITLE
【开发经验题】2个php-cgi进程都new实例化一个类，在执行时，类里面的变量、函数等是共用的，还是独占？

### ISSUE THREAD

**Issue by phpforlan** [phpforlan/ArtisanPHP#3]
【开发经验题】2个php-cgi进程都new实例化一个类，在执行时，类里面的变量、函数等是共用的，还是独占？或者说更多的php-cgi进程实例化new这个类，当然他们都在执行中。

注：这个类被同时实例化了，并且都还没有执行完毕。

**Comment by jayxhj** [comment]
非共享，每个进程占有自己的资源。
